import { useSyncExternalStore } from "react";

export type Theme = "light" | "dark" | "system";
export type Locale = "zh" | "en";

const messages: Record<Locale, Record<string, string>> = {
  zh: {
    brand: "Zero",
    "menu.overview": "概览",
    "menu.requirements": "需求管理",
    "menu.runtime": "Runtime 运行时管理",
    "menu.agents": "智能体管理",
    "workspace.placeholder": "主工作区（占位）",
    collapse: "收起侧边栏",
    expand: "展开侧边栏",
    "theme.title": "主题",
    "theme.light": "浅色",
    "theme.dark": "深色",
    "theme.system": "跟随系统",
    "lang.title": "语言",
    "user.name": "管理员",
    "user.email": "admin@zero.local",
    "user.profile": "个人资料",
    "user.settings": "设置",
    "user.logout": "退出登录",
    "workspace.label": "工作空间",
    "workspace.create": "创建工作空间",
    "auth.loginTitle": "登录 Zero",
    "auth.registerTitle": "注册 Zero",
    "auth.email": "邮箱",
    "auth.emailPh": "you@example.com",
    "auth.password": "密码",
    "auth.passwordPh": "至少 6 位",
    "auth.name": "昵称",
    "auth.namePh": "留空将用邮箱前缀",
    "auth.loginBtn": "登录",
    "auth.registerBtn": "注册",
    "auth.toRegister": "还没有账号？去注册",
    "auth.toLogin": "已有账号？去登录",
    "auth.submitting": "提交中…",
    "ws.createTitle": "创建工作空间",
    "ws.createDesc": "工作空间用于隔离你的需求、运行时与智能体。",
    "ws.namePh": "为工作空间起个名字",
    "ws.descPh": "描述（可选）",
    "ws.createBtn": "创建",
    "ws.creating": "创建中…",
    "ws.emptyTitle": "还没有工作空间",
    "ws.emptyHint": "创建第一个工作空间以开始使用。",
    "common.cancel": "取消",
    "common.retry": "重试",

    // 侧边栏动作
    "nav.search": "搜索…",
    "nav.newIssue": "新建 issue",

    // 搜索
    "search.placeholder": "搜索 issue…",
    "search.commands": "快捷命令",
    "search.issuesGroup": "Issues",
    "search.recent": "最近",
    "search.searching": "搜索中…",
    "search.empty": "没有匹配的 issue",

    // 需求 / issue
    "issue.create": "新建 Issue",
    "issue.creating": "创建中…",
    "issue.newTitle": "新建需求",
    "issue.titlePh": "需求标题",
    "issue.descPh": "补充详细描述（支持 Markdown）…",
    "issue.submitHint": "⌘↵ 快速创建",
    "issue.assign": "指派",
    "issue.unassigned": "未指派",
    "issue.members": "成员",
    "issue.agentsSoon": "智能体 · 即将上线",
    "issue.listTitle": "我的需求",
    "issue.emptyTitle": "还没有需求",
    "issue.emptyHint": "新建第一个需求，开始追踪你的开发任务。",

    // 状态
    "status.backlog": "待规划",
    "status.todo": "待办",
    "status.in_progress": "进行中",
    "status.in_review": "评审中",
    "status.done": "已完成",
    "status.cancelled": "已取消",

    // 优先级
    "priority.urgent": "紧急",
    "priority.high": "高",
    "priority.medium": "中",
    "priority.low": "低",
    "priority.none": "无",

    // 详情页 / 时间线
    "detail.back": "返回",
    "detail.notFound": "需求不存在或已被删除",
    "detail.descPh": "添加描述…（支持 Markdown）",
    "detail.activity": "活动",
    "detail.properties": "属性",
    "detail.commentPh": "写下评论…（⌘↵ 发送）",
    "detail.send": "评论",
    "detail.posting": "发送中…",
    "detail.details": "详情",
    "detail.created": "创建于",
    "detail.updated": "更新于",
    "issue.lastActivity": "最新活动",
    "prop.status": "状态",
    "prop.priority": "优先级",
    "prop.assignee": "指派",
    "prop.repo": "仓库",
    "timeline.system": "系统",
    "timeline.created": "创建了该需求",
    "timeline.status": "将状态从 {from} 改为 {to}",
    "timeline.priority": "将优先级从 {from} 改为 {to}",
    "timeline.assigned": "指派给 {name}",
    "timeline.unassigned": "取消了指派",
    "timeline.runStarted": "开始执行",
    "timeline.runFinished": "执行完成",
    "timeline.runFailed": "执行失败",
    "timeline.noRuntime": "未绑定运行时，无法执行",

    // 执行日志 / 运行
    "run.status.queued": "排队中",
    "run.status.running": "执行中",
    "run.status.succeeded": "已完成",
    "run.status.failed": "失败",
    "run.status.cancelled": "已取消",
    "runlog.events": "事件",
    "runlog.toolCalls": "工具调用",
    "runlog.viewLog": "查看执行日志",
    "runlog.copyAll": "复制全部",
    "runlog.copied": "已复制",
    "runlog.empty": "暂无执行事件",
    "runlog.filter.all": "全部",
    "runlog.filter.text": "文本",
    "runlog.filter.tools": "工具",
    "runlog.filter.errors": "错误",
    "repo.bind": "绑定仓库",
    "repo.unbind": "解绑仓库",
    "repo.add": "添加仓库…",
    "repo.addTitle": "添加仓库",
    "repo.addDesc": "登记一个 Git 仓库地址或本地路径，供需求绑定。",
    "repo.namePh": "仓库名（如 zero）",
    "repo.urlPh": "git URL 或本地路径",
    "repo.branchDefaultPh": "默认分支（默认 main）",
    "repo.branchPh": "基准分支，如 main",
    "repo.create": "添加",
    "repo.creating": "添加中…",
    "binding.label": "工作区",
    "binding.none": "不绑（空目录）",
    "binding.repo": "仓库",
    "binding.repoSection": "仓库（隔离 worktree）",
    "binding.dirSection": "工作目录（就地）",
    "binding.addRepo": "添加仓库…",
    "binding.bindDir": "绑工作目录…",
    "binding.dirPh": "本地文件夹绝对路径，如 /Users/you/code",
    "binding.confirm": "确定",
    "binding.browse": "浏览",
    "binding.browseErr": "打不开选择器（daemon 没运行？）—— 请手动输入路径",
    "binding.worktreeHint": "隔离 worktree · 主副本不动",
    "binding.inPlaceHint": "就地 · 不隔离，直接改此目录",
    "binding.emptyHint": "临时空目录 · 适合新项目/纯对话",

    // 智能体
    "issue.agents": "智能体",
    "issue.noAgents": "还没有智能体",
    "agents.title": "智能体",
    "agents.new": "新建智能体",
    "agents.empty": "还没有智能体",
    "agents.emptyHint": "创建一个智能体，之后可把需求指派给它。",
    "agents.formNewTitle": "新建智能体",
    "agents.formEditTitle": "编辑智能体",
    "agents.name": "名称",
    "agents.namePh": "智能体名称（如 后端-Claude）",
    "agents.provider": "底层工具",
    "agents.model": "模型",
    "agents.modelPh": "可选，如 claude-opus-4-8",
    "agents.instructions": "系统指令",
    "agents.instructionsPh": "给这个智能体的角色/规则（可选）",
    "agents.create": "创建",
    "agents.creating": "创建中…",
    "agents.save": "保存",
    "agents.saving": "保存中…",
    "agents.edit": "编辑",
    "agents.delete": "删除",
    "agents.deleteConfirm": "确定删除该智能体？它在需求上的指派会被解除。",
    "agents.noRuntime": "未绑定运行时",
    "agents.runtime": "运行时",
    "agents.noRuntimeBind": "未绑定",

    // 运行时
    "runtime.title": "运行时",
    "runtime.subtitle": "运行时是执行智能体的地方——在你机器上跑一个 daemon，它会发现本地的 Claude Code 等工具并连上来。",
    "runtime.add": "添加运行时",
    "runtime.empty": "还没有运行时",
    "runtime.emptyHint": "添加一个运行时，然后在你的机器上运行 daemon 连接它。",
    "runtime.online": "在线",
    "runtime.offline": "离线",
    "runtime.notConnected": "尚未连接",
    "runtime.delete": "删除",
    "runtime.deleteConfirm": "确定删除该运行时？绑定它的智能体会被解绑。",
    "runtime.addTitle": "添加运行时",
    "runtime.addDesc": "给运行时起个名字（如 我的 Mac）。",
    "runtime.namePh": "运行时名称",
    "runtime.create": "创建",
    "runtime.creating": "创建中…",
    "runtime.pairTitle": "配对运行时",
    "runtime.pairDesc": "在你的机器上运行下面的命令，daemon 会连上来并发现本地工具。",
    "runtime.command": "配对命令",
    "runtime.token": "令牌",
    "runtime.tokenOnce": "令牌只显示这一次，请妥善保存。",
    "runtime.done": "完成",
    // 可见性 / 作用域
    "runtime.visibility": "谁能用",
    "runtime.visPrivate": "仅自己",
    "runtime.visWorkspace": "工作空间共享",
    "runtime.visPrivateHint": "仅你本人可见和使用。",
    "runtime.visWorkspaceHint": "上架到的工作空间内全员可用。",
    "runtime.reach": "在哪些工作空间",
    "runtime.reachHint": "运行时上架到这些工作空间（至少含当前）。仅归属者可调整。",
    "runtime.reachCount": "{n} 个工作空间",
    "runtime.concurrency": "并发上限",
    "runtime.concurrencyHint": "同时最多并行的任务数（1 = 串行）。",
    "runtime.owner": "归属",
    "runtime.you": "你",
    "runtime.edit": "编辑",
    "runtime.editTitle": "编辑运行时",
    "runtime.save": "保存",
    "runtime.saving": "保存中…",
    "runtime.private": "私有",
    "runtime.shared": "共享",
    "runtime.agentsBound": "{n} 个智能体",
    // 详情页
    "runtime.back": "返回运行时",
    "runtime.notFound": "运行时不存在或无权访问",
    "runtime.secBasic": "基本信息",
    "runtime.secReach": "触达范围",
    "runtime.secAgents": "绑定的智能体",
    "runtime.noAgents": "还没有智能体绑定到该运行时。",
    "runtime.secUsage": "用量与成本",
    "runtime.usageWindow": "近 30 天 · 仅本工作空间",
    "runtime.cost": "成本",
    "runtime.runs": "执行次数",
    "runtime.tokens": "Token",
    "runtime.inputTokens": "输入",
    "runtime.outputTokens": "输出",
    "runtime.cacheTokens": "缓存",
    "runtime.byDay": "按天",
    "runtime.byAgent": "按智能体",
    "runtime.noUsage": "近 30 天本工作空间还没有用量。",
    "runtime.noCostHint":
      "其中 {n} 次为订阅计费·无金额数据（如 Codex 走 ChatGPT 订阅，已排除在成本外）",
    "runtime.detachConfirm": "从当前工作空间下架该运行时？本空间内绑定它的智能体会被解绑（不影响其它工作空间）。",
    "runtime.deleteOwnConfirm": "删除该运行时？所有工作空间内绑定它的智能体都会被解绑，用量记录一并删除。",
    "runtime.kind": "类型",
    "runtime.heartbeat": "最近心跳",
  },
  en: {
    brand: "Zero",
    "menu.overview": "Overview",
    "menu.requirements": "Requirements",
    "menu.runtime": "Runtime",
    "menu.agents": "Agents",
    "workspace.placeholder": "Main workspace (placeholder)",
    collapse: "Collapse sidebar",
    expand: "Expand sidebar",
    "theme.title": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "lang.title": "Language",
    "user.name": "Admin",
    "user.email": "admin@zero.local",
    "user.profile": "Profile",
    "user.settings": "Settings",
    "user.logout": "Log out",
    "workspace.label": "Workspaces",
    "workspace.create": "Create workspace",
    "auth.loginTitle": "Sign in to Zero",
    "auth.registerTitle": "Sign up for Zero",
    "auth.email": "Email",
    "auth.emailPh": "you@example.com",
    "auth.password": "Password",
    "auth.passwordPh": "At least 6 characters",
    "auth.name": "Name",
    "auth.namePh": "Leave blank to use email prefix",
    "auth.loginBtn": "Sign in",
    "auth.registerBtn": "Sign up",
    "auth.toRegister": "No account? Sign up",
    "auth.toLogin": "Have an account? Sign in",
    "auth.submitting": "Submitting…",
    "ws.createTitle": "Create workspace",
    "ws.createDesc": "Workspaces isolate your requirements, runtimes and agents.",
    "ws.namePh": "Name your workspace",
    "ws.descPh": "Description (optional)",
    "ws.createBtn": "Create",
    "ws.creating": "Creating…",
    "ws.emptyTitle": "No workspace yet",
    "ws.emptyHint": "Create your first workspace to get started.",
    "common.cancel": "Cancel",
    "common.retry": "Retry",

    "nav.search": "Search…",
    "nav.newIssue": "New issue",

    "search.placeholder": "Search issues…",
    "search.commands": "Commands",
    "search.issuesGroup": "Issues",
    "search.recent": "Recent",
    "search.searching": "Searching…",
    "search.empty": "No matching issues",

    "issue.create": "New Issue",
    "issue.creating": "Creating…",
    "issue.newTitle": "New issue",
    "issue.titlePh": "Issue title",
    "issue.descPh": "Add a detailed description (Markdown supported)…",
    "issue.submitHint": "⌘↵ to create",
    "issue.assign": "Assign",
    "issue.unassigned": "Unassigned",
    "issue.members": "Members",
    "issue.agentsSoon": "Agents · coming soon",
    "issue.listTitle": "My Issues",
    "issue.emptyTitle": "No issues yet",
    "issue.emptyHint": "Create your first issue to start tracking work.",

    "status.backlog": "Backlog",
    "status.todo": "Todo",
    "status.in_progress": "In Progress",
    "status.in_review": "In Review",
    "status.done": "Done",
    "status.cancelled": "Cancelled",

    "priority.urgent": "Urgent",
    "priority.high": "High",
    "priority.medium": "Medium",
    "priority.low": "Low",
    "priority.none": "None",

    "detail.back": "Back",
    "detail.notFound": "Issue not found or deleted",
    "detail.descPh": "Add a description… (Markdown supported)",
    "detail.activity": "Activity",
    "detail.properties": "Properties",
    "detail.commentPh": "Leave a comment… (⌘↵ to send)",
    "detail.send": "Comment",
    "detail.posting": "Sending…",
    "detail.details": "Details",
    "detail.created": "Created",
    "detail.updated": "Updated",
    "issue.lastActivity": "Last activity",
    "prop.status": "Status",
    "prop.priority": "Priority",
    "prop.assignee": "Assignee",
    "prop.repo": "Repository",
    "timeline.system": "System",
    "timeline.created": "created this issue",
    "timeline.status": "changed status from {from} to {to}",
    "timeline.priority": "changed priority from {from} to {to}",
    "timeline.assigned": "assigned to {name}",
    "timeline.unassigned": "removed the assignee",
    "timeline.runStarted": "started a run",
    "timeline.runFinished": "finished the run",
    "timeline.runFailed": "run failed",
    "timeline.noRuntime": "no runtime bound; cannot run",

    "run.status.queued": "Queued",
    "run.status.running": "Running",
    "run.status.succeeded": "Done",
    "run.status.failed": "Failed",
    "run.status.cancelled": "Cancelled",
    "runlog.events": "events",
    "runlog.toolCalls": "tool calls",
    "runlog.viewLog": "View run log",
    "runlog.copyAll": "Copy all",
    "runlog.copied": "Copied",
    "runlog.empty": "No events yet",
    "runlog.filter.all": "All",
    "runlog.filter.text": "Text",
    "runlog.filter.tools": "Tools",
    "runlog.filter.errors": "Errors",
    "repo.bind": "Bind repo",
    "repo.unbind": "Unbind repo",
    "repo.add": "Add repo…",
    "repo.addTitle": "Add repository",
    "repo.addDesc": "Register a Git URL or local path for issues to bind to.",
    "repo.namePh": "Repo name (e.g. zero)",
    "repo.urlPh": "git URL or local path",
    "repo.branchDefaultPh": "Default branch (defaults to main)",
    "repo.branchPh": "Base branch, e.g. main",
    "repo.create": "Add",
    "repo.creating": "Adding…",
    "binding.label": "Workspace",
    "binding.none": "None (empty dir)",
    "binding.repo": "Repo",
    "binding.repoSection": "Repository (isolated worktree)",
    "binding.dirSection": "Working directory (in-place)",
    "binding.addRepo": "Add repo…",
    "binding.bindDir": "Bind working dir…",
    "binding.dirPh": "Absolute local folder path, e.g. /Users/you/code",
    "binding.confirm": "OK",
    "binding.browse": "Browse",
    "binding.browseErr": "Picker unavailable (daemon not running?) — type the path",
    "binding.worktreeHint": "Isolated worktree · main checkout untouched",
    "binding.inPlaceHint": "In-place · not isolated, edits this folder",
    "binding.emptyHint": "Temp empty dir · for new projects / chat",

    "issue.agents": "Agents",
    "issue.noAgents": "No agents yet",
    "agents.title": "Agents",
    "agents.new": "New agent",
    "agents.empty": "No agents yet",
    "agents.emptyHint": "Create an agent, then assign issues to it.",
    "agents.formNewTitle": "New agent",
    "agents.formEditTitle": "Edit agent",
    "agents.name": "Name",
    "agents.namePh": "Agent name (e.g. backend-Claude)",
    "agents.provider": "Provider",
    "agents.model": "Model",
    "agents.modelPh": "Optional, e.g. claude-opus-4-8",
    "agents.instructions": "Instructions",
    "agents.instructionsPh": "Role / rules for this agent (optional)",
    "agents.create": "Create",
    "agents.creating": "Creating…",
    "agents.save": "Save",
    "agents.saving": "Saving…",
    "agents.edit": "Edit",
    "agents.delete": "Delete",
    "agents.deleteConfirm": "Delete this agent? Its issue assignments will be cleared.",
    "agents.noRuntime": "No runtime bound",
    "agents.runtime": "Runtime",
    "agents.noRuntimeBind": "Not bound",

    "runtime.title": "Runtimes",
    "runtime.subtitle": "A runtime is where agents run — start a daemon on your machine and it discovers local Claude Code etc. and connects.",
    "runtime.add": "Add runtime",
    "runtime.empty": "No runtimes yet",
    "runtime.emptyHint": "Add a runtime, then run the daemon on your machine to connect it.",
    "runtime.online": "Online",
    "runtime.offline": "Offline",
    "runtime.notConnected": "Not connected",
    "runtime.delete": "Delete",
    "runtime.deleteConfirm": "Delete this runtime? Agents bound to it will be unbound.",
    "runtime.addTitle": "Add runtime",
    "runtime.addDesc": "Give the runtime a name (e.g. My Mac).",
    "runtime.namePh": "Runtime name",
    "runtime.create": "Create",
    "runtime.creating": "Creating…",
    "runtime.pairTitle": "Pair runtime",
    "runtime.pairDesc": "Run the command below on your machine; the daemon connects and discovers local tools.",
    "runtime.command": "Pairing command",
    "runtime.token": "Token",
    "runtime.tokenOnce": "The token is shown only once — keep it safe.",
    "runtime.done": "Done",
    "runtime.visibility": "Who can use",
    "runtime.visPrivate": "Only me",
    "runtime.visWorkspace": "Workspace",
    "runtime.visPrivateHint": "Visible to and usable by you only.",
    "runtime.visWorkspaceHint": "Usable by everyone in the workspaces it's listed in.",
    "runtime.reach": "In which workspaces",
    "runtime.reachHint": "Workspaces this runtime is listed in (always includes the current one). Owner only.",
    "runtime.reachCount": "{n} workspaces",
    "runtime.concurrency": "Max concurrency",
    "runtime.concurrencyHint": "Max tasks run in parallel (1 = serial).",
    "runtime.owner": "Owner",
    "runtime.you": "you",
    "runtime.edit": "Edit",
    "runtime.editTitle": "Edit runtime",
    "runtime.save": "Save",
    "runtime.saving": "Saving…",
    "runtime.private": "Private",
    "runtime.shared": "Shared",
    "runtime.agentsBound": "{n} agents",
    "runtime.back": "Back to runtimes",
    "runtime.notFound": "Runtime not found or no access",
    "runtime.secBasic": "Basics",
    "runtime.secReach": "Reach",
    "runtime.secAgents": "Bound agents",
    "runtime.noAgents": "No agents are bound to this runtime yet.",
    "runtime.secUsage": "Usage & cost",
    "runtime.usageWindow": "Last 30 days · this workspace only",
    "runtime.cost": "Cost",
    "runtime.runs": "Runs",
    "runtime.tokens": "Tokens",
    "runtime.inputTokens": "Input",
    "runtime.outputTokens": "Output",
    "runtime.cacheTokens": "Cache",
    "runtime.byDay": "By day",
    "runtime.byAgent": "By agent",
    "runtime.noUsage": "No usage in this workspace in the last 30 days.",
    "runtime.noCostHint":
      "{n} run(s) have no price data (e.g. Codex via ChatGPT subscription — excluded from cost)",
    "runtime.detachConfirm": "Remove this runtime from the current workspace? Agents bound to it here will be unbound (other workspaces unaffected).",
    "runtime.deleteOwnConfirm": "Delete this runtime? Agents bound to it in all workspaces will be unbound and usage records removed.",
    "runtime.kind": "Kind",
    "runtime.heartbeat": "Last heartbeat",
  },
};

function readTheme(): Theme {
  const v = localStorage.getItem("zero-theme");
  return v === "light" || v === "dark" || v === "system" ? v : "system";
}

function readLocale(): Locale {
  const v = localStorage.getItem("zero-locale");
  return v === "zh" || v === "en" ? v : "zh";
}

const mql = window.matchMedia("(prefers-color-scheme: dark)");

const state = {
  theme: readTheme(),
  locale: readLocale(),
  systemDark: mql.matches,
};

// ---- 简易外部 store：订阅 / 快照 ----
const listeners = new Set<() => void>();

function emit(): void {
  for (const fn of listeners) fn();
}

function subscribe(fn: () => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function resolvedDark(): boolean {
  return state.theme === "dark" || (state.theme === "system" && state.systemDark);
}

function applyTheme(): void {
  document.documentElement.classList.toggle("dark", resolvedDark());
}

mql.addEventListener("change", (e) => {
  state.systemDark = e.matches;
  if (state.theme === "system") {
    applyTheme();
    emit();
  }
});

// 初始化：应用主题与语言
applyTheme();
document.documentElement.lang = state.locale === "zh" ? "zh-CN" : "en";

export function setTheme(theme: Theme): void {
  state.theme = theme;
  localStorage.setItem("zero-theme", theme);
  applyTheme();
  emit();
}

export function setLocale(locale: Locale): void {
  state.locale = locale;
  localStorage.setItem("zero-locale", locale);
  document.documentElement.lang = locale === "zh" ? "zh-CN" : "en";
  emit();
}

export function useUi() {
  // 任一字段变化即触发重渲染；快照用拼接字符串保证引用稳定
  const snapshot = useSyncExternalStore(
    subscribe,
    () => `${state.theme}|${state.locale}|${state.systemDark}`,
  );
  void snapshot;

  const t = (key: string): string => messages[state.locale][key] ?? key;

  return {
    theme: state.theme,
    locale: state.locale,
    isDark: resolvedDark(),
    setTheme,
    setLocale,
    t,
  };
}
